-- KALENSARI STORE V10.4 - DATABASE PESANAN + PRODUK
-- Jalankan seluruh file ini di Supabase > SQL Editor.

create table if not exists public.products (
  id bigint primary key,
  name text not null,
  price integer not null default 0,
  sale integer,
  category text not null default 'Makanan',
  unit text,
  seller text,
  status text not null default 'Show',
  image text
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_code text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  customer_name text,
  customer_phone text,
  address text,
  note text,
  payment text,
  items jsonb not null default '[]'::jsonb,
  subtotal integer not null default 0,
  shipping integer not null default 0,
  total integer not null default 0,
  status text not null default 'menunggu'
);

alter table public.orders add column if not exists order_code text;
alter table public.orders add column if not exists created_at timestamptz default now();
alter table public.orders add column if not exists updated_at timestamptz;
alter table public.orders add column if not exists customer_name text;
alter table public.orders add column if not exists customer_phone text;
alter table public.orders add column if not exists address text;
alter table public.orders add column if not exists note text;
alter table public.orders add column if not exists payment text;
alter table public.orders add column if not exists items jsonb default '[]'::jsonb;
alter table public.orders add column if not exists subtotal integer default 0;
alter table public.orders add column if not exists shipping integer default 0;
alter table public.orders add column if not exists total integer default 0;
alter table public.orders add column if not exists status text default 'menunggu';

update public.orders set status='menunggu' where status is null or lower(status)='baru';

create unique index if not exists orders_order_code_idx on public.orders(order_code);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_status_idx on public.orders(status);

alter table public.products enable row level security;
alter table public.orders enable row level security;

grant select, insert, update, delete on public.products to anon, authenticated;
grant select, insert, update on public.orders to anon, authenticated;

-- Produk: website perlu membaca dan admin browser perlu menyimpan perubahan.
drop policy if exists "products_public_read" on public.products;
create policy "products_public_read" on public.products for select to anon, authenticated using (true);
drop policy if exists "products_public_insert" on public.products;
create policy "products_public_insert" on public.products for insert to anon, authenticated with check (true);
drop policy if exists "products_public_update" on public.products;
create policy "products_public_update" on public.products for update to anon, authenticated using (true) with check (true);
drop policy if exists "products_public_delete" on public.products;
create policy "products_public_delete" on public.products for delete to anon, authenticated using (true);

-- Pesanan: pelanggan boleh membuat dan membaca pesanan; admin browser boleh mengubah status.
drop policy if exists "orders_public_insert" on public.orders;
create policy "orders_public_insert" on public.orders for insert to anon, authenticated with check (true);
drop policy if exists "orders_public_select" on public.orders;
create policy "orders_public_select" on public.orders for select to anon, authenticated using (true);
drop policy if exists "orders_public_update" on public.orders;
create policy "orders_public_update" on public.orders for update to anon, authenticated using (true) with check (true);

-- Catatan keamanan: policy SELECT/UPDATE publik dipakai karena versi ini masih memakai PIN admin di browser.
-- Setelah fungsi sudah stabil, sebaiknya admin dipindahkan ke Supabase Auth dan policy publik dipersempit.
