create table if not exists public.products (
  id bigint primary key,
  name text not null,
  price integer not null default 0,
  sale integer,
  category text not null,
  unit text,
  seller text,
  status text not null default 'Show',
  image text
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_code text unique,
  created_at timestamptz not null default now(),
  customer_name text,
  customer_phone text,
  address text,
  note text,
  payment text,
  items jsonb not null,
  subtotal integer not null default 0,
  shipping integer not null default 0,
  total integer not null default 0,
  status text not null default 'baru'
);

alter table public.products enable row level security;
alter table public.orders enable row level security;

drop policy if exists "products_public_read" on public.products;
create policy "products_public_read" on public.products for select using (true);

drop policy if exists "products_public_write" on public.products;
create policy "products_public_write" on public.products for insert with check (true);

drop policy if exists "products_public_update" on public.products;
create policy "products_public_update" on public.products for update using (true) with check (true);

drop policy if exists "products_public_delete" on public.products;
create policy "products_public_delete" on public.products for delete using (true);

drop policy if exists "orders_public_insert" on public.orders;
create policy "orders_public_insert" on public.orders for insert with check (true);

drop policy if exists "orders_public_read" on public.orders;
create policy "orders_public_read" on public.orders for select using (true);

-- V9: izin admin/status pesanan melalui REST API yang digunakan aplikasi
drop policy if exists "orders_public_update" on public.orders;
create policy "orders_public_update" on public.orders for update using (true) with check (true);

-- Jika tabel orders sudah ada dari V8, jalankan ini sekali:
alter table public.orders add column if not exists order_code text;
create unique index if not exists orders_order_code_idx on public.orders(order_code);


-- V10: indeks untuk pengelolaan status pesanan
create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_created_at_idx on public.orders(created_at desc);

-- Status yang digunakan aplikasi:
-- baru = Menunggu, diproses = Diproses, dikirim = Dikirim,
-- selesai = Selesai, dibatalkan = Dibatalkan
