create table if not exists public.products (
  id bigint primary key,
  name text not null,
  price integer not null default 0,
  sale integer,
  category text not null,
  unit text,
  seller text,
  status text not null default 'Show',
  image text
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_name text,
  customer_phone text,
  address text,
  note text,
  payment text,
  items jsonb not null,
  subtotal integer not null default 0,
  shipping integer not null default 0,
  total integer not null default 0,
  status text not null default 'baru'
);

alter table public.products enable row level security;
alter table public.orders enable row level security;

drop policy if exists "products_public_read" on public.products;
create policy "products_public_read" on public.products for select using (true);

drop policy if exists "products_public_write" on public.products;
create policy "products_public_write" on public.products for insert with check (true);

drop policy if exists "products_public_update" on public.products;
create policy "products_public_update" on public.products for update using (true) with check (true);

drop policy if exists "products_public_delete" on public.products;
create policy "products_public_delete" on public.products for delete using (true);

drop policy if exists "orders_public_insert" on public.orders;
create policy "orders_public_insert" on public.orders for insert with check (true);

drop policy if exists "orders_public_read" on public.orders;
create policy "orders_public_read" on public.orders for select using (true);
